travis:
  secure:
    BINSTAR_TOKEN: jFPmeNtlHLjcQ+oVPzD/SUxPZlgSL7fbcSrc0r9VVXjdjyq8ycEAtMzwo29GGn0qIfpbmY/WTuDOZzKqISnXlp7sEluuqq9mkeQhUKf1H7eFmimvqkoA0bpONNTx+8sIqEWVBNqItLf56KrETBtpE2OsVUQncldmtY8VahQqAv3VMkqDowOTL9cqxjJpX50+nksj8w2yrhUBBb52A4ftoK618ajjfZb2jwDr9YA3AzMR2xv5uppJFb6tfhQQpjJ98QH5ujY0QnR7brjZr1bTvufARYgLPH5ubwSdWeghBm9ZnU+TjMYxOwpVtHKd9625rrwRfXfqxWQGapFNCYf46R/0gu2RMVVizZL1mi1g3CARSNKk3ZM+YVmO6j2pereqK1FfC0MGjIiPiRWouaFdZs9CVFxNVCPt4tRKqK1OPDzNivcGvi3wSHMdRyV1EYWjMoz6huV1z0siK5WKnBmYlDid1XpvFq3Cy9pOyqK8pbKqtjMmGMW3dao/l5BnTLWUCGFPBFQtb50HrqbyAjbfuoohU+cZYDYoZ5Bqxs9bMvuXLRQI7rllwuz0IY6yYuFrhrNnEMvbjf1/XVDPhDzB7y+jgTF5Vac1qpEwQCSfRxEjiUJPj1HGa/t4PI70mfPBrmnEAlGMdkbVVE7iICk1RMdR+yoYtNigOAkeCMujdVA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
